const movies = [
    {
     title: "Burning of Durland's Riding Academy",
     year: 1902,
     cast: [],
     genres: ["Documentary", "Short"],
   },
   {
     title: "The Interrupted Bathers",
     year: 1902,
     cast: [],
     genres: ["Comedy", "Short"],
   },
   {
    title: "Eddie the Eagle",
    year: 2016,
    cast: ["Taron Egerton", "Hugh Jackman", "Christopher Walken"],
    genres: ["Sports", "Drama", "Comedy"],
  },
  {
    title: "Zootopia",
    year: 2016,
    cast: ["Ginnifer Goodwin", "Jason Bateman", "Idris Elba"],
    genres: ["Animated", "Adventure"],
  },
  {
    title: "Wind River",
    year: 2017,
    cast: ["Jeremy Renner", "Elizabeth Olsen", "Jon Bernthal", "Kelsey Chow"],
    genres: ["Drama", "Thriller"],
  },
  {
    title: "Armed Response",
    year: 2017,
    cast: [
      "Wesley Snipes",
      "Anne Heche",
      "Dave Annable",
      "Seth Rollins",
      "Gene Simmons",
      "Mo Gallini",
    ],
    genres: ["Thriller", "Science Fiction", "Action"],
  },
  {
    title: "Red Sparrow",
    year: 2018,
    cast: [
      "Jennifer Lawrence",
      "Joel Edgerton",
      "Matthias Schoenaerts",
      "Charlotte Rampling",
      "Mary-Louise Parker",
      "Jeremy Irons",
    ],
    genres: ["Action", "Drama", "Mystery", "Thriller"],
  },
  {
    title: "Pickings",
    year: 2018,
    cast: ["Elyse Price", "Joel Bernard", "Katie Vincent", "Joe Trombino"],
    genres: ["Crime", "Drama"],
  },
  {
    title: "Bumblebee",
    year: 2018,
    cast: [
      "Hailee Steinfeld",
      "John Cena",
      "Jorge Lendeborg Jr.",
      "Jason Drucker",
      "Rachel Crow",
      "Pamela Adlon",
    ],
    genres: ["Action", "Adventure", "Science Fiction"],
  },
  {
    title: "Welcome to Marwen",
    year: 2018,
    cast: [
      "Steve Carell",
      "Leslie Mann",
      "Diane Kruger",
      "Falk Hentschel",
      "Janelle Monáe",
      "Eiza Gonzalez",
      "Gwendoline Christie",
    ],
    genres: ["Fantasy", "Drama"],
  },
  {
    title: "Holmes and Watson",
    year: 2018,
    cast: [
      "Will Ferrell",
      "John C. Reilly",
      "Rebecca Hall",
      "Ralph Fiennes",
      "Rob Brydon",
      "Kelly Macdonald",
      "Lauren Lapkus",
      "Hugh Laurie",
    ],
    genres: ["Action", "Mystery", "Comedy"],
  },
  ]
